changelog:
  categories:
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Chores"
      labels:
        - "chore"
        - "build"
        - "ci"
  exclude:
    labels:
      - "skip-release"
